<a href="https://colab.research.google.com/github/TechySanj/PYTHON_Basics/blob/main/NumpyOperations(Sca).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Elementwise Operations
1.Basic Operations
with Scalars

In [ ]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [ ]:
a**2

array([ 1,  4,  9, 16])

All arithmetic opeates elementwise

In [ ]:
a=np.array([1,2,3,4])
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [ ]:
a*b

array([2., 4., 6., 8.])

In [ ]:
c=np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Matrix Multiplication
c=np.diag([1,2,3,4])
print(c*c)
print('************')
print(c.dot(c)) #To multiply 2 matrices

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


Comarisons

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [ ]:
a>b

array([False, False,  True, False])

In [ ]:
#Arraywise comparisons
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,b)

False

In [ ]:
np.array_equal(a,c)

True

Logical Operators

In [ ]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,1], dtype=bool)
np.logical_or(a,b)
np.logical_and(a,b)

array([ True, False, False, False])

Transcendental Functions

In [ ]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.log(a)

<ipython-input-14-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

Shape Mismatch

In [ ]:
a=np.arange(4)
a+np.array([1,2]) #cant be done


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Basic Reductions

Computing Sums

In [ ]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [ ]:
#sum by rows and by columns
x= np.array([[1,1],[2,2]])
x
x.sum(axis=0)

array([3, 3])

In [ ]:
x.sum(axis=1)

array([2, 4])

Other reductions

In [ ]:
x= np.array([1,3,2])
x.min()
x.max()
x.argmin() #index of minimum element
x.argmax() #index of maximum element

1

Logical Operations

In [ ]:
np.all([True,False,False]) #logical AND
np.any([True,False,False]) #logical OR

True